### ISSUE TITLE
14.4 Array apply: apply

### ISSUE THREAD

**Issue by grossbuch5** [kingaa/R_Tutorial#2]
please, explain how  `apply(A,c(1,2),function (x, y) sum(x>y),y=8)` works

**Comment by kingaa** [comment]
Let
```
f <- function (x, y) sum(x > y)
```
Since in this case `A` is a 3 x 5 x 2 array, 
```
apply(A,c(1,2),function (x, y) sum(x>y),y=8)
```
is equivalent to
```
result <- array(3,5)

for (i=seq_len(3) {
  for (j=seq_len(5)) {
     result[i,j] <- f(A[i,j,],y=8)
  }
}
```

As always, the first argument to the function is the slice of the array `A`.  Additional arguments to this function can be passed by supplying these as additional arguments to `apply`.  Thus, in this case, the fourth argument (`y=8`) in the call to `apply` is passed as a second argument to the function.

In the tutorial, I've left this as an exercise for the reader.  I've edited the text to make this clearer.
